// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function avg(a, b) {
  return (a + b) / 2.0;
}

console.log("Average of 3 and 4", (3.0 + 4.0) / 2.0);

console.log("Average of 3?!", (function (param) {
        return avg(3.0, param);
      }));

function call(country, area, number) {
  return country + (" " + (area + (" " + number)));
}

console.log("Call Vasia at", "+7 702 116 30 10");

function callKazahstan(param, param$1) {
  return call("+7", param, param$1);
}

function callActiv(param) {
  return call("+7", "702", param);
}

console.log("Call Germany:", callKazahstan);

console.log("Call Berlin:", callActiv);

console.log("Call something in Kazahstan:", "+7 702 116 30 10");

console.log("Call something in Activ:", "+7 702 116 30 10");

exports.avg = avg;
exports.call = call;
exports.callKazahstan = callKazahstan;
exports.callActiv = callActiv;
/*  Not a pure module */
