// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function payment(principal, apr, years) {
  var r = apr / 12.0 / 100.0;
  var n = Math.imul(years, 12);
  var powerTerm = Math.pow(1.0 + r, n);
  return principal * (r * powerTerm) / (powerTerm - 1.0);
}

function usPayment(param) {
  return function (param$1) {
    return payment(param, param$1, 30);
  };
}

function ukPayment(param) {
  return function (param$1) {
    return payment(param, param$1, 25);
  };
}

function dePayment(param) {
  return function (param$1) {
    return payment(param, param$1, 20);
  };
}

function toFixed(prim, prim$1) {
  return prim.toFixed(prim$1);
}

console.log("Loan of 10000 at 5%");

function func(param, param$1) {
  return payment(10000.0, param, param$1);
}

console.log("US: $", Curry._2(func, 5.0, 30).toFixed(2));

function func$1(param, param$1) {
  return payment(10000.0, param, param$1);
}

console.log("UK: £", Curry._2(func$1, 5.0, 30).toFixed(2));

function func$2(param, param$1) {
  return payment(10000.0, param, param$1);
}

console.log("DE: €", Curry._2(func$2, 5.0, 30).toFixed(2));

exports.payment = payment;
exports.usPayment = usPayment;
exports.ukPayment = ukPayment;
exports.dePayment = dePayment;
exports.toFixed = toFixed;
/*  Not a pure module */
