// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function avg(a, b) {
  return (a + b) / 2.0;
}

var result = (3.0 + 4.5) / 2.0;

console.log(result);

exports.avg = avg;
exports.result = result;
/*  Not a pure module */
