// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function payment(principal, apr, years) {
  var r = apr / 12.0 / 100.0;
  var n = Math.imul(years, 12);
  var powerTerm = Math.pow(1.0 + r, n);
  return principal * (r * powerTerm) / (powerTerm - 1.0);
}

var amount = payment(10000.0, 5.0, 30);

console.log("Anount per month: $", amount.toFixed(2));

exports.payment = payment;
exports.amount = amount;
/* amount Not a pure module */
